### ISSUE TITLE
struct.error: unpack requires a string argument of length 64

### ISSUE THREAD

**Issue by GoogleCodeExporter** [aguaviva/micro-jpeg-visualizer#1]
```
Running the script gives the following output:

Traceback (most recent call last):
  File "micro-jpeg-visualizer.py", line 282, in <module>
    j.decode(open('images/porsche.jpg', 'r').read())
  File "micro-jpeg-visualizer.py", line 262, in decode
    self.DefineQuantizationTables(chunk)
  File "micro-jpeg-visualizer.py", line 214, in DefineQuantizationTables
    self.quant[hdr & 0xf] =  GetArray("B", data[1:1+64],64)
  File "micro-jpeg-visualizer.py", line 36, in GetArray
    return      list(unpack(s,l[:length]))
struct.error: unpack requires a string argument of length 64


Python version using: Python 2.7.2 (default, Jun 12 2011, 15:08:59) [MSC v.1500 
32 bit (Intel)] on win
32


```

Original issue reported on code.google.com by `alexei....@gmail.com` on 5 Jan 2012 at 11:47

**Comment by aguaviva** [comment]
the file was open as ascii and not as bin, not sure why it worked for so long
