### ISSUE TITLE
 unsupported operand type(s) for >>: 'str' and 'int'

### ISSUE THREAD

**Issue by windlessStorm** [aguaviva/micro-jpeg-visualizer#3]
## Problem:
Getting type mismatch error when trying to run it.

`Traceback (most recent call last):
  File "micro-jpeg-visualizer.py", line 280, in <module>
    jpeg().decode(open('images/porsche.jpg', 'rb').read())
  File "micro-jpeg-visualizer.py", line 267, in decode
    lenchunk = self.StartOfScan(data, lenchunk)
  File "micro-jpeg-visualizer.py", line 204, in StartOfScan
    matL, oldlumdccoeff = self.BuildMatrix(st,0, self.quant[self.quantMapping[0]], oldlumdccoeff)
  File "micro-jpeg-visualizer.py", line 173, in BuildMatrix
    code = self.tables[0+idx].GetCode(st)
  File "micro-jpeg-visualizer.py", line 156, in GetCode
    res = self.Find(st)
  File "micro-jpeg-visualizer.py", line 151, in Find
    r=r[st.GetBit()]
  File "micro-jpeg-visualizer.py", line 112, in GetBit
    return (b >> s) & 1
TypeError: unsupported operand type(s) for >>: 'str' and 'int'`

## Setup:
Windows 10
Python 3.6

**Comment by aguaviva** [comment]
hey, I am using python 3.6.6 and the code as it is runs fine, same for others. What do you think is different in your set up?
